name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup environment
      uses: ./.github/actions/setup-env

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r third-party/duplicate-code-detection-tool/requirements.txt
        python -m nltk.downloader punkt punkt_tab

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX=$HOME/.local

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --target install

    - name: Run C++ E2E tests
      run: |
        source venv/bin/activate || call venv\Scripts\activate
        ./build/arkanjo-test

    - name: Run CLI integration tests
      run: |
        source venv/bin/activate || call venv\Scripts\activate
        echo -e "tests/e2e/codebase\n0.9\n1" | arkanjo preprocessor build
        arkanjo explorer
        arkanjo duplication

    - name: Upload build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: arkanjo-cli-${{ matrix.os }}
        path: |
          build/arkanjo
          build/arkanjo-preprocessor